"""Generate a realistic MESSY Excel file simulating dirty client data (customer orders)."""
import random
import numpy as np
import pandas as pd
from openpyxl import Workbook

# Seed for reproducible messy data
random.seed(42)
np.random.seed(42)

OUTPUT = "samples/messy_input.xlsx"
N_ROWS = 400

# Pools of realistic-ish values
FIRST = ["John", "maria", "AHMED", "  Sofia", "Liam ", "Olivia", "noah", "EMMA", "Lucas", "mia"]
LAST = ["smith", "JONES", " Garcia", "Brown ", "patel", "WONG", "silva", "Costa", "müller", "rossi"]
CITIES = ["lisbon", "PORTO", " Madrid", "Berlin ", "paris", "ROME", "london", "amsterdam"]
PRODUCTS = ["Laptop", "MOUSE", " keyboard", "Monitor ", "webcam", "HEADSET", "usb cable", "docking station"]
STATUS = ["shipped", "PENDING", " cancelled", "Delivered ", "returned"]

# Mixed date formats stored as TEXT
def messy_date():
    base = pd.Timestamp("2023-01-01") + pd.Timedelta(days=random.randint(0, 700))
    fmt = random.choice(["%Y-%m-%d", "%d/%m/%Y", "%m-%d-%Y", "%d %b %Y", "%Y/%m/%d"])
    return base.strftime(fmt)

# Numbers stored as text with currency symbols / thousands separators
def messy_price():
    val = round(random.uniform(5, 2500), 2)
    style = random.choice(["plain", "euro", "dollar", "thousands", "spaces"])
    if style == "euro":
        return f"€{val:.2f}"
    if style == "dollar":
        return f"${val:,.2f}"
    if style == "thousands":
        return f"{val:,.2f}"
    if style == "spaces":
        return f"  {val:.2f} "
    return str(val)

rows = []
for i in range(N_ROWS):
    rows.append({
        "Order ID": 1000 + i,
        "Customer First": random.choice(FIRST),
        "Customer Last": random.choice(LAST),
        "City": random.choice(CITIES),
        "Product": random.choice(PRODUCTS),
        "Quantity": random.choice([1, 2, 3, "5", " 4 ", 10]),  # mixed int / text
        "Unit Price": messy_price(),
        "Order Date": messy_date(),
        "Status": random.choice(STATUS),
        "Notes": random.choice(["", "  ", "VIP", "fragile ", None]),  # mostly empty
        "Blank Col": None,  # fully empty column
    })

df = pd.DataFrame(rows)

# Inject missing values randomly into a few columns
for col in ["City", "Unit Price", "Status"]:
    idx = df.sample(frac=0.08, random_state=1).index
    df.loc[idx, col] = np.nan

# Inject duplicate rows (copy ~20 existing rows)
dupes = df.sample(20, random_state=2).copy()
df = pd.concat([df, dupes], ignore_index=True)

# Inject a few fully-empty rows
for _ in range(5):
    df.loc[len(df)] = [np.nan] * df.shape[1]

# Shuffle so dupes/empties are scattered
df = df.sample(frac=1, random_state=3).reset_index(drop=True)

# Write manually with openpyxl so we can add a JUNK header row above real headers
wb = Workbook()
ws = wb.active
ws.title = "Orders"

# Junk title row above the real header
ws.append(["Acme Corp - Q3 Orders Export", None, None, "Generated by legacy system", None, None, None, None, None, None, None])
# Real header row
ws.append(list(df.columns))
# Data rows
for _, r in df.iterrows():
    ws.append(list(r.values))

wb.save(OUTPUT)
print(f"Wrote {OUTPUT}: {len(df)} data rows + 1 junk row + 1 header row, {df.shape[1]} columns")
